[package]
name = "awwsy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "1.0.1"
thiserror = "1.0.50"
aws-sdk-s3 = { version = "1.4.0", optional = true }
tracing = "0.1.40"

[features]
default = []
s3 = ["dep:aws-sdk-s3"]
